name: alarm
description: A simple Flutter alarm manager plugin for both iOS and Android.
version: 1.0.5
homepage: https://github.com/gdelataillade/alarm

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  android_alarm_manager_plus: 
    git:
      url: https://github.com/yoct1994/plus_plugins.git
      path: packages/android_alarm_manager_plus
      
  flutter:
    sdk: flutter
  flutter_fgbg: ^0.2.2
  flutter_local_notifications: ^14.0.0+1
  just_audio: ^0.9.32
  plugin_platform_interface: ^2.1.4
  shared_preferences: ^2.1.0
  timezone: ^0.9.2
  vibration: ^1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gdelataillade.alarm.alarm
        pluginClass: AlarmPlugin
      ios:
        pluginClass: AlarmPlugin
